[build]
  command = "echo 'No build required for Python Flask app'"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "."
  
# Note: This is a Flask application that requires server-side processing
# For full functionality, consider using platforms like Railway, Render, or Heroku
# that support Python Flask applications with real-time features
